"""Initial Phase 1 learning tracker schema"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision = "099ba6615cba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('MANAGER','EMPLOYEE')", name="ck_user_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "metadata", sa.JSON().with_variant(JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_entity_date",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "courses",
        sa.Column("course_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=150), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "estimated_duration_minutes IS NULL OR estimated_duration_minutes >= 0",
            name="ck_course_duration",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_code"),
    )
    op.create_table(
        "learning_tracks",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("manager_user_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["manager_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "employees",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("employee_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("department", sa.String(length=150), nullable=False),
        sa.Column("designation", sa.String(length=150), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_code"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_employees_department"), "employees", ["department"], unique=False
    )
    op.create_index(
        op.f("ix_employees_team_id"), "employees", ["team_id"], unique=False
    )
    op.create_table(
        "learning_track_courses",
        sa.Column("learning_track_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("sequence_order > 0", name="ck_track_order"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["learning_track_id"], ["learning_tracks.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("learning_track_id", "course_id"),
        sa.UniqueConstraint(
            "learning_track_id", "sequence_order", name="uq_track_order"
        ),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"], ["refresh_tokens.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["auth_sessions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_session_id"),
        "refresh_tokens",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "course_learning_attempts",
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("in_progress_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("completed_by", sa.String(length=36), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'COMPLETED' AND completion_date IS NOT NULL AND completed_by IS NOT NULL) OR (status <> 'COMPLETED' AND completion_date IS NULL AND completed_by IS NULL)",
            name="ck_attempt_completion",
        ),
        sa.CheckConstraint(
            "status IN ('NOT_STARTED','ENROLLED','IN_PROGRESS','COMPLETED')",
            name="ck_attempt_status",
        ),
        sa.ForeignKeyConstraint(["completed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "employee_id", "course_id", name="uq_attempt_identity"
        ),
    )
    op.create_index(
        op.f("ix_course_learning_attempts_course_id"),
        "course_learning_attempts",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_learning_attempts_employee_id"),
        "course_learning_attempts",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_learning_attempts_status"),
        "course_learning_attempts",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_active_attempt",
        "course_learning_attempts",
        ["employee_id", "course_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'COMPLETED' AND retired_at IS NULL"),
        sqlite_where=sa.text("status <> 'COMPLETED' AND retired_at IS NULL"),
    )
    op.create_table(
        "learning_assignments",
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=True),
        sa.Column("learning_track_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_by", sa.String(length=36), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("employee_can_update", sa.Boolean(), nullable=False),
        sa.Column("employee_can_complete", sa.Boolean(), nullable=False),
        sa.Column("certificate_required", sa.Boolean(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.String(length=36), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(course_id IS NOT NULL AND learning_track_id IS NULL) OR (course_id IS NULL AND learning_track_id IS NOT NULL)",
            name="ck_assignment_target",
        ),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["cancelled_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["learning_track_id"], ["learning_tracks.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "employee_id", name="uq_assignment_employee"),
    )
    op.create_index(
        op.f("ix_learning_assignments_employee_id"),
        "learning_assignments",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_assignments_target_date"),
        "learning_assignments",
        ["target_date"],
        unique=False,
    )
    op.create_table(
        "assignment_courses",
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("course_id", sa.String(length=36), nullable=False),
        sa.Column("learning_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("target_date_override", sa.Date(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence_order > 0", name="ck_assignment_order"),
        sa.ForeignKeyConstraint(
            ["assignment_id", "employee_id"],
            ["learning_assignments.id", "learning_assignments.employee_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["learning_attempt_id", "employee_id", "course_id"],
            [
                "course_learning_attempts.id",
                "course_learning_attempts.employee_id",
                "course_learning_attempts.course_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "course_id", name="uq_assignment_course"),
        sa.UniqueConstraint(
            "assignment_id", "sequence_order", name="uq_assignment_order"
        ),
    )
    op.create_index(
        op.f("ix_assignment_courses_assignment_id"),
        "assignment_courses",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_courses_course_id"),
        "assignment_courses",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_courses_learning_attempt_id"),
        "assignment_courses",
        ["learning_attempt_id"],
        unique=False,
    )
    op.create_table(
        "certificates",
        sa.Column("learning_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("blob_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by", sa.String(length=36), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=36), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("file_size > 0", name="ck_certificate_size"),
        sa.ForeignKeyConstraint(
            ["learning_attempt_id"],
            ["course_learning_attempts.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["revoked_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_key"),
    )
    op.create_index(
        op.f("ix_certificates_learning_attempt_id"),
        "certificates",
        ["learning_attempt_id"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """CREATE FUNCTION reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'audit logs are append-only'; END; $$"""
        )
        op.execute(
            "CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation()"
        )
    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER audit_append_only ON audit_logs")
        op.execute("DROP FUNCTION reject_audit_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_certificates_learning_attempt_id"), table_name="certificates"
    )
    op.drop_table("certificates")
    op.drop_index(
        op.f("ix_assignment_courses_learning_attempt_id"),
        table_name="assignment_courses",
    )
    op.drop_index(
        op.f("ix_assignment_courses_course_id"), table_name="assignment_courses"
    )
    op.drop_index(
        op.f("ix_assignment_courses_assignment_id"), table_name="assignment_courses"
    )
    op.drop_table("assignment_courses")
    op.drop_index(
        op.f("ix_learning_assignments_target_date"), table_name="learning_assignments"
    )
    op.drop_index(
        op.f("ix_learning_assignments_employee_id"), table_name="learning_assignments"
    )
    op.drop_table("learning_assignments")
    op.drop_index(
        "uq_active_attempt",
        table_name="course_learning_attempts",
        postgresql_where=sa.text("status <> 'COMPLETED' AND retired_at IS NULL"),
        sqlite_where=sa.text("status <> 'COMPLETED' AND retired_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_course_learning_attempts_status"),
        table_name="course_learning_attempts",
    )
    op.drop_index(
        op.f("ix_course_learning_attempts_employee_id"),
        table_name="course_learning_attempts",
    )
    op.drop_index(
        op.f("ix_course_learning_attempts_course_id"),
        table_name="course_learning_attempts",
    )
    op.drop_table("course_learning_attempts")
    op.drop_index(op.f("ix_refresh_tokens_session_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("learning_track_courses")
    op.drop_index(op.f("ix_employees_team_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_department"), table_name="employees")
    op.drop_table("employees")
    op.drop_table("teams")
    op.drop_table("learning_tracks")
    op.drop_table("courses")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_entity_date", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    # ### end Alembic commands ###
